# updated 20201003 -- A. Conaty to include all FP satellites and instruments
#
sensor = {
   'airs': 'AIRS',
   'amsua': 'AMSUA',
   'amsr2': 'AMSR2',
   'amsub': 'AMSU-B',
   'atms': 'ATMS',
   'avhrr': 'AVHRR',
   'cris': 'CrIS',
   'cris-fsr': 'CrIS',
   'gmi': 'GMI',
   'iasi': 'IASI',
   'hirs4': 'HIRS4',
   'mhs': 'MHS',
   'seviri': 'SEVIRI',
   'ssmis':   'SSMIS',
}

satellite = {
    'f17': 'F17',
    'f18': 'F18',
    'm08': 'METEOSAT-8',
    'm09': 'METEOSAT-9',
    'm10': 'METEOSAT-10',
    'n06': 'NOAA-6',
    'n07': 'NOAA-7',
    'n08': 'NOAA-8',
    'n09': 'NOAA-9',
    'n10': 'NOAA-10',
    'n11': 'NOAA-11',
    'n12': 'NOAA-12',
    'n13': 'NOAA-13',
    'n14': 'NOAA-14',
    'n15': 'NOAA-15',
    'n16': 'NOAA-16',
    'n17': 'NOAA-17',
    'n18': 'NOAA-18',
    'n19': 'NOAA-19',
    'n20': 'NOAA-20',
    'n21': 'NOAA-21',
    'n22': 'NOAA-22',
    'n23': 'NOAA-23',
    'npp': 'SNPP',
    'aqua': 'AQUA',
    'gpm': 'GPM',
    'metop-a': 'METOP-A',
    'metop-b': 'METOP-B',
    'metop-c': 'METOP-C',
    'gcom-w1': 'GCOM-W',
}
